
services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: spoticom
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    env_file:
      - .env
    container_name: fastapi_app
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:123456@db:5432/spoticom
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
      - ./alembic/versions:/app/alembic/versions
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data:
