"""New changes

Revision ID: 16c130564f7a
Revises: 1772a0d5109e
Create Date: 2025-02-21 12:06:27.715903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "16c130564f7a"
down_revision = "1772a0d5109e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(
        op.f("ix_users_hashed_password"), "users", ["hashed_password"], unique=False
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=False)
    op.drop_index("ix_user_email", table_name="user")
    op.drop_index("ix_user_hashed_password", table_name="user")
    op.drop_index("ix_user_id", table_name="user")
    op.drop_index("ix_user_username", table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("hashed_password", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="user_pkey"),
    )
    op.create_index("ix_user_username", "user", ["username"], unique=False)
    op.create_index("ix_user_id", "user", ["id"], unique=False)
    op.create_index(
        "ix_user_hashed_password", "user", ["hashed_password"], unique=False
    )
    op.create_index("ix_user_email", "user", ["email"], unique=False)
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_hashed_password"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
