"""init

Revision ID: 1772a0d5109e
Revises: 35e4fe426949
Create Date: 2025-02-21 11:54:34.750432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1772a0d5109e'
down_revision = '35e4fe426949'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
