"""new

Revision ID: 592ef19e51b6
Revises: 9565ed3eae20
Create Date: 2025-02-22 18:44:02.239580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592ef19e51b6'
down_revision = '9565ed3eae20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
