"""Updated schema

Revision ID: 6c2fc74b4830
Revises: adcc286e95a0
Create Date: 2025-02-09 15:05:02.298489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c2fc74b4830'
down_revision = 'adcc286e95a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('fake_column2', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'fake_column2')
    # ### end Alembic commands ###
