"""update

Revision ID: 93e0edf66c30
Revises: 17b2bb76af8f
Create Date: 2025-02-22 08:41:43.029911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e0edf66c30'
down_revision = '17b2bb76af8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
