"""new migration

Revision ID: 9565ed3eae20
Revises: d088aad7bb1e
Create Date: 2025-02-22 14:50:32.752219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9565ed3eae20'
down_revision = 'd088aad7bb1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
