"""Updated schema

Revision ID: adcc286e95a0
Revises: 343d2d1f2747
Create Date: 2025-02-09 15:02:48.654820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adcc286e95a0'
down_revision = '343d2d1f2747'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
