"""

Revision ID: ae7021b3edfd
Revises: ed35e3091ad2
Create Date: 2025-02-22 14:43:01.361894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ae7021b3edfd"
down_revision = "ed35e3091ad2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
