"""new migration

Revision ID: d088aad7bb1e
Revises: ae7021b3edfd
Create Date: 2025-02-22 14:44:25.741737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd088aad7bb1e'
down_revision = 'ae7021b3edfd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
