"""New changes

Revision ID: eb3731af8704
Revises: 16c130564f7a
Create Date: 2025-02-21 12:28:15.838167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eb3731af8704"
down_revision = "16c130564f7a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
