"""Updated schema

Revision ID: eda3f468f0a2
Revises: a0971a931f56
Create Date: 2025-02-09 15:10:43.591482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eda3f468f0a2'
down_revision = 'a0971a931f56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('fake_column2', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'fake_column2')
    # ### end Alembic commands ###
